/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['HealthController_check'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/audit-logs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AuditController_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/imports/{spec}/template': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ImportsController_template'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/imports/{spec}/preview': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['ImportsController_preview'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/imports/{spec}/commit': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['ImportsController_commit'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/exports/{spec}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ImportsController_export'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/signup': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AuthController_signup'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AuthController_login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AuthController_refresh'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AuthController_logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AuthController_me'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/switch-company': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AuthController_switchCompany'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/companies': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['CompaniesController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/companies/current': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['CompaniesController_current'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['CompaniesController_update'];
    trace?: never;
  };
  '/api/business-places': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['CompaniesController_listPlaces'];
    put?: never;
    post: operations['CompaniesController_createPlace'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/business-places/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations['CompaniesController_removePlace'];
    options?: never;
    head?: never;
    patch: operations['CompaniesController_updatePlace'];
    trace?: never;
  };
  '/api/invitations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['CompaniesController_listInvitations'];
    put?: never;
    post: operations['CompaniesController_invite'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/invitations/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations['CompaniesController_revokeInvitation'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/invitations/lookup': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['CompaniesController_lookupInvitation'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/invitations/accept': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['CompaniesController_acceptInvitation'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/roles': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AccessController_roles'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/roles/{role}/permissions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations['AccessController_updateRole'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/members': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AccessController_members'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/members/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['AccessController_updateMember'];
    trace?: never;
  };
  '/api/settings/modules': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['SettingsController_modules'];
    put: operations['SettingsController_updateModules'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/integrations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['IntegrationsController_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/integrations/{channel}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations['IntegrationsController_update'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/integrations/{channel}/test': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['IntegrationsController_test'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/files': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['FilesController_upload'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/files/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['FilesController_meta'];
    put?: never;
    post?: never;
    delete: operations['FilesController_remove'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/files/{id}/download': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['FilesController_download'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  HealthController_check: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description DB·Redis 연결 상태 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {string} */
            status: 'ok' | 'degraded';
            /** @enum {string} */
            db: 'ok' | 'error';
            /** @enum {string} */
            redis: 'ok' | 'error';
          };
        };
      };
    };
  };
  AuditController_list: {
    parameters: {
      query?: {
        limit?: number;
        before?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 최신순. 다음 페이지는 before=마지막 createdAt */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            createdAt: string;
            action: string;
            entity: string | null;
            entityId: string | null;
            method: string | null;
            path: string | null;
            statusCode: number | null;
            ip: string | null;
            userName: string | null;
            userEmail: string | null;
            before: unknown;
            after: unknown;
          }[];
        };
      };
      /** @description 권한 필요: settings.audit (read) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ImportsController_template: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        spec: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ImportsController_preview: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        spec: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': {
          /** Format: binary */
          file: string;
        };
      };
    };
    responses: {
      /** @description 행별 검증 결과(등록하지 않음) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            total: number;
            valid: number;
            invalid: number;
            missingHeaders: string[];
            rows: {
              rowNumber: number;
              values: {
                [key: string]: string;
              };
              errors: {
                field: string;
                message: string;
              }[];
            }[];
          };
        };
      };
    };
  };
  ImportsController_commit: {
    parameters: {
      query: {
        skipInvalid: string;
      };
      header?: never;
      path: {
        spec: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': {
          /** Format: binary */
          file: string;
        };
      };
    };
    responses: {
      /** @description skipInvalid=true 이면 오류 행을 건너뛰고 등록 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            created: number;
            updated: number;
            skipped: number;
          };
        };
      };
    };
  };
  ImportsController_export: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        spec: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_signup: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          email: string;
          password: string;
          name: string;
        };
      };
    };
    responses: {
      /** @description 가입 후 바로 로그인된다 */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            user: {
              /** Format: uuid */
              id: string;
              email: string;
              name: string;
            };
            /** Format: uuid */
            companyId: string | null;
            accessToken?: string;
            refreshToken?: string;
          };
        };
      };
    };
  };
  AuthController_login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          email: string;
          password: string;
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            user: {
              /** Format: uuid */
              id: string;
              email: string;
              name: string;
            };
            /** Format: uuid */
            companyId: string | null;
            accessToken?: string;
            refreshToken?: string;
          };
        };
      };
    };
  };
  AuthController_refresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          refreshToken?: string;
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json':
            | {
                user: {
                  /** Format: uuid */
                  id: string;
                  email: string;
                  name: string;
                };
                /** Format: uuid */
                companyId: string | null;
                accessToken?: string;
                refreshToken?: string;
              }
            | {
                /** @enum {boolean} */
                ok: true;
              };
        };
      };
    };
  };
  AuthController_logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          refreshToken?: string;
        };
      };
    };
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 현재 사용자·회사·권한 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            user: {
              /** Format: uuid */
              id: string;
              email: string;
              name: string;
            };
            company: {
              /** Format: uuid */
              id: string;
              name: string;
              bizRegNo: string;
            } | null;
            /** @enum {string|null} */
            role: 'owner' | 'admin' | 'accountant' | 'approver' | 'employee' | null;
            companies: {
              /** Format: uuid */
              id: string;
              name: string;
              /** @enum {string} */
              role: 'owner' | 'admin' | 'accountant' | 'approver' | 'employee';
            }[];
            permissions: {
              [key: string]: 'none' | 'read' | 'write';
            };
            enabledModules: {
              [key: string]: boolean;
            };
          };
        };
      };
    };
  };
  AuthController_switchCompany: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** Format: uuid */
          companyId: string;
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            user: {
              /** Format: uuid */
              id: string;
              email: string;
              name: string;
            };
            company: {
              /** Format: uuid */
              id: string;
              name: string;
              bizRegNo: string;
            } | null;
            /** @enum {string|null} */
            role: 'owner' | 'admin' | 'accountant' | 'approver' | 'employee' | null;
            companies: {
              /** Format: uuid */
              id: string;
              name: string;
              /** @enum {string} */
              role: 'owner' | 'admin' | 'accountant' | 'approver' | 'employee';
            }[];
            permissions: {
              [key: string]: 'none' | 'read' | 'write';
            };
            enabledModules: {
              [key: string]: boolean;
            };
          };
        };
      };
    };
  };
  CompaniesController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          name: string;
          bizRegNo: string;
          representative?: string;
          businessType?: string;
          businessItem?: string;
          address?: string;
          phone?: string;
        };
      };
    };
    responses: {
      /** @description 만든 회사로 바로 전환된다 */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            company: {
              /** Format: uuid */
              id: string;
              name: string;
              bizRegNo: string;
              representative: string | null;
              businessType: string | null;
              businessItem: string | null;
              address: string | null;
              phone: string | null;
              fiscalYearStartMonth: number;
            };
            accessToken?: string;
          };
        };
      };
    };
  };
  CompaniesController_current: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            name: string;
            bizRegNo: string;
            representative: string | null;
            businessType: string | null;
            businessItem: string | null;
            address: string | null;
            phone: string | null;
            fiscalYearStartMonth: number;
          };
        };
      };
      /** @description 권한 필요: settings.company (read) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CompaniesController_update: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          name?: string;
          bizRegNo?: string;
          representative?: string | null;
          businessType?: string | null;
          businessItem?: string | null;
          address?: string | null;
          phone?: string | null;
          fiscalYearStartMonth?: number;
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            name: string;
            bizRegNo: string;
            representative: string | null;
            businessType: string | null;
            businessItem: string | null;
            address: string | null;
            phone: string | null;
            fiscalYearStartMonth: number;
          };
        };
      };
      /** @description 권한 필요: settings.company (write) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CompaniesController_listPlaces: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            name: string;
            bizRegNo: string;
            representative: string | null;
            businessType: string | null;
            businessItem: string | null;
            address: string | null;
            isHeadquarters: boolean;
          }[];
        };
      };
      /** @description 권한 필요: settings.company (read) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CompaniesController_createPlace: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          name: string;
          bizRegNo: string;
          representative?: string | null;
          businessType?: string | null;
          businessItem?: string | null;
          address?: string | null;
        };
      };
    };
    responses: {
      /** @description OK */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            name: string;
            bizRegNo: string;
            representative: string | null;
            businessType: string | null;
            businessItem: string | null;
            address: string | null;
            isHeadquarters: boolean;
          };
        };
      };
      /** @description 권한 필요: settings.company (write) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CompaniesController_removePlace: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 권한 필요: settings.company (write) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CompaniesController_updatePlace: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          name?: string;
          bizRegNo?: string;
          representative?: string | null;
          businessType?: string | null;
          businessItem?: string | null;
          address?: string | null;
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            name: string;
            bizRegNo: string;
            representative: string | null;
            businessType: string | null;
            businessItem: string | null;
            address: string | null;
            isHeadquarters: boolean;
          };
        };
      };
      /** @description 권한 필요: settings.company (write) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CompaniesController_listInvitations: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            email: string;
            /** @enum {string} */
            role: 'owner' | 'admin' | 'accountant' | 'approver' | 'employee';
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            createdAt: string;
          }[];
        };
      };
      /** @description 권한 필요: settings.users (read) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CompaniesController_invite: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          email: string;
          /** @enum {string} */
          role: 'admin' | 'accountant' | 'approver' | 'employee';
        };
      };
    };
    responses: {
      /** @description 초대 메일을 보낸다 */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            email: string;
            /** @enum {string} */
            role: 'owner' | 'admin' | 'accountant' | 'approver' | 'employee';
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            createdAt: string;
          };
        };
      };
      /** @description 권한 필요: settings.users (write) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CompaniesController_revokeInvitation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 권한 필요: settings.users (write) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CompaniesController_lookupInvitation: {
    parameters: {
      query: {
        token: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            companyName: string;
            email: string;
            /** @enum {string} */
            role: 'owner' | 'admin' | 'accountant' | 'approver' | 'employee';
            /** @enum {string} */
            status: 'pending' | 'accepted' | 'expired' | 'revoked';
          };
        };
      };
    };
  };
  CompaniesController_acceptInvitation: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          token: string;
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            companyId: string;
            accessToken?: string;
          };
        };
      };
    };
  };
  AccessController_roles: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 역할별 권한 매트릭스 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {string} */
            role: 'owner' | 'admin' | 'accountant' | 'approver' | 'employee';
            editable: boolean;
            overridden: boolean;
            permissions: {
              /** @enum {string} */
              dashboard: 'none' | 'read' | 'write';
              /** @enum {string} */
              accounting: 'none' | 'read' | 'write';
              /** @enum {string} */
              evidence: 'none' | 'read' | 'write';
              /** @enum {string} */
              sales: 'none' | 'read' | 'write';
              /** @enum {string} */
              production: 'none' | 'read' | 'write';
              /** @enum {string} */
              approval: 'none' | 'read' | 'write';
              /** @enum {string} */
              hr: 'none' | 'read' | 'write';
              /** @enum {string} */
              attendance: 'none' | 'read' | 'write';
              /** @enum {string} */
              payroll: 'none' | 'read' | 'write';
              /** @enum {string} */
              tax: 'none' | 'read' | 'write';
              /** @enum {string} */
              settings: 'none' | 'read' | 'write';
              /** @enum {string} */
              'settings.company': 'none' | 'read' | 'write';
              /** @enum {string} */
              'settings.users': 'none' | 'read' | 'write';
              /** @enum {string} */
              'settings.menus': 'none' | 'read' | 'write';
              /** @enum {string} */
              'settings.integrations': 'none' | 'read' | 'write';
              /** @enum {string} */
              'settings.audit': 'none' | 'read' | 'write';
            };
          }[];
        };
      };
      /** @description 권한 필요: settings.users (read) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AccessController_updateRole: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        role: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          permissions: {
            /** @enum {string} */
            dashboard?: 'none' | 'read' | 'write';
            /** @enum {string} */
            accounting?: 'none' | 'read' | 'write';
            /** @enum {string} */
            evidence?: 'none' | 'read' | 'write';
            /** @enum {string} */
            sales?: 'none' | 'read' | 'write';
            /** @enum {string} */
            production?: 'none' | 'read' | 'write';
            /** @enum {string} */
            approval?: 'none' | 'read' | 'write';
            /** @enum {string} */
            hr?: 'none' | 'read' | 'write';
            /** @enum {string} */
            attendance?: 'none' | 'read' | 'write';
            /** @enum {string} */
            payroll?: 'none' | 'read' | 'write';
            /** @enum {string} */
            tax?: 'none' | 'read' | 'write';
            /** @enum {string} */
            settings?: 'none' | 'read' | 'write';
            /** @enum {string} */
            'settings.company'?: 'none' | 'read' | 'write';
            /** @enum {string} */
            'settings.users'?: 'none' | 'read' | 'write';
            /** @enum {string} */
            'settings.menus'?: 'none' | 'read' | 'write';
            /** @enum {string} */
            'settings.integrations'?: 'none' | 'read' | 'write';
            /** @enum {string} */
            'settings.audit'?: 'none' | 'read' | 'write';
          };
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {string} */
            role: 'owner' | 'admin' | 'accountant' | 'approver' | 'employee';
            editable: boolean;
            overridden: boolean;
            permissions: {
              /** @enum {string} */
              dashboard: 'none' | 'read' | 'write';
              /** @enum {string} */
              accounting: 'none' | 'read' | 'write';
              /** @enum {string} */
              evidence: 'none' | 'read' | 'write';
              /** @enum {string} */
              sales: 'none' | 'read' | 'write';
              /** @enum {string} */
              production: 'none' | 'read' | 'write';
              /** @enum {string} */
              approval: 'none' | 'read' | 'write';
              /** @enum {string} */
              hr: 'none' | 'read' | 'write';
              /** @enum {string} */
              attendance: 'none' | 'read' | 'write';
              /** @enum {string} */
              payroll: 'none' | 'read' | 'write';
              /** @enum {string} */
              tax: 'none' | 'read' | 'write';
              /** @enum {string} */
              settings: 'none' | 'read' | 'write';
              /** @enum {string} */
              'settings.company': 'none' | 'read' | 'write';
              /** @enum {string} */
              'settings.users': 'none' | 'read' | 'write';
              /** @enum {string} */
              'settings.menus': 'none' | 'read' | 'write';
              /** @enum {string} */
              'settings.integrations': 'none' | 'read' | 'write';
              /** @enum {string} */
              'settings.audit': 'none' | 'read' | 'write';
            };
          };
        };
      };
      /** @description 권한 필요: settings.users (write) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AccessController_members: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            userId: string;
            name: string;
            email: string;
            /** @enum {string} */
            role: 'owner' | 'admin' | 'accountant' | 'approver' | 'employee';
            /** @enum {string} */
            status: 'active' | 'disabled';
            /** Format: date-time */
            createdAt: string;
            isMe: boolean;
          }[];
        };
      };
      /** @description 권한 필요: settings.users (read) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AccessController_updateMember: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** @enum {string} */
          role?: 'owner' | 'admin' | 'accountant' | 'approver' | 'employee';
          /** @enum {string} */
          status?: 'active' | 'disabled';
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            role: 'owner' | 'admin' | 'accountant' | 'approver' | 'employee';
            /** @enum {string} */
            status: 'active' | 'disabled';
          };
        };
      };
      /** @description 권한 필요: settings.users (write) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  SettingsController_modules: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 메뉴(업무 모듈) 사용 여부 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            key: string;
            label: string;
            phase: string;
            available: boolean;
            required: boolean;
            enabled: boolean;
          }[];
        };
      };
      /** @description 권한 필요: settings.menus (read) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  SettingsController_updateModules: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          enabledModules: {
            [key: string]: boolean;
          };
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            key: string;
            label: string;
            phase: string;
            available: boolean;
            required: boolean;
            enabled: boolean;
          }[];
        };
      };
      /** @description 권한 필요: settings.menus (write) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  IntegrationsController_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 채널별 연동 상태(자격증명은 마스킹) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {string} */
            channel: 'bank' | 'card' | 'hometax' | 'taxinvoice' | 'ocr' | 'ai';
            enabled: boolean;
            provider: string;
            credentials: {
              [key: string]: string;
            };
            /** @enum {string} */
            schedule: 'manual' | 'hourly' | 'daily';
            /** @enum {string|null} */
            lastStatus: 'success' | 'error' | null;
            lastMessage: string | null;
            /** Format: date-time */
            lastRunAt: string | null;
          }[];
        };
      };
      /** @description 권한 필요: settings.integrations (read) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  IntegrationsController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        channel: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          enabled: boolean;
          provider: string;
          credentials?: {
            [key: string]: string;
          };
          /** @enum {string} */
          schedule?: 'manual' | 'hourly' | 'daily';
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {string} */
            channel: 'bank' | 'card' | 'hometax' | 'taxinvoice' | 'ocr' | 'ai';
            enabled: boolean;
            provider: string;
            credentials: {
              [key: string]: string;
            };
            /** @enum {string} */
            schedule: 'manual' | 'hourly' | 'daily';
            /** @enum {string|null} */
            lastStatus: 'success' | 'error' | null;
            lastMessage: string | null;
            /** Format: date-time */
            lastRunAt: string | null;
          };
        };
      };
      /** @description 권한 필요: settings.integrations (write) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  IntegrationsController_test: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        channel: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 저장된 설정으로 연결 테스트 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            ok: boolean;
            message: string;
          };
        };
      };
      /** @description 권한 필요: settings.integrations (write) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FilesController_upload: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': {
          /** Format: binary */
          file: string;
        };
      };
    };
    responses: {
      /** @description OK */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            filename: string;
            mimeType: string;
            sizeBytes: number;
            sha256: string;
            /** Format: date-time */
            createdAt: string;
          };
        };
      };
    };
  };
  FilesController_meta: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            filename: string;
            mimeType: string;
            sizeBytes: number;
            sha256: string;
            /** Format: date-time */
            createdAt: string;
          };
        };
      };
    };
  };
  FilesController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FilesController_download: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
